wandb_version: 1

exp.model.depth:
  value: 1
exp.model.in_size:
  value: 1
exp.model.key._target_:
  value: jax.random.PRNGKey
exp.model.key.seed:
  value: 0
exp.model.out_size:
  value: 1
exp.model.width_size:
  value: 15
opt.batchsize:
  value: 10000
opt.epochs:
  value: 20000
opt.l0_threshold:
  value: 0.001
opt.loss_type:
  value: mse
opt.lr_start:
  value: 0.0001
