defaults:
  - _self_
  - sweep: sweep

in_size: 3
out_size: 1
width_size: 21
depth: 2
_target_: jax.random.PRNGKey
seed: 1

epochs: 20000
batchsize: 10000
loss_type: 'mse'
lr_start: 1e-3
l0_threshold: 1e-3

wandb:
  setup:
    entity: simonb03-university-of-t-bingen

