wandb_version: 1

in_size:
  desc: null
  value: 4
out_size:
  desc: null
  value: 1
width_size:
  desc: null
  value: 21
depth:
  desc: null
  value: 2
_target_:
  desc: null
  value: jax.random.PRNGKey
seed:
  desc: null
  value: 9
epochs:
  desc: null
  value: 20000
batchsize:
  desc: null
  value: 10000
loss_type:
  desc: null
  value: mse
lr_start:
  desc: null
  value: 0.001
l0_threshold:
  desc: null
  value: 0.001
wandb:
  desc: null
  value:
    setup:
      entity: simonb03-university-of-t-bingen
sweep:
  desc: null
  value:
    program: main_OPR.py
    name: validation_sweep_OPR_4
    metric:
      name: val_loss
      goal: minimize
    method: grid
    parameters:
      in_size:
        value: 4
      out_size:
        value: 1
      width_size:
        value: 21
      depth:
        value: 2
      _target_:
        value: jax.random.PRNGKey
      seed:
        values:
        - 0
        - 1
        - 3
        - 5
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
      epochs:
        value: 20000
      batchsize:
        value: 10000
      loss_type:
        value: mse
      lr_start:
        value: 0.001
      l0_threshold:
        value: 0.001
    command:
    - C:/Users/Simon/.conda/envs/EQL/python.exe
    - main_OPR.py
_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742309452
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      - 37
      4: 3.11.11
      5: 0.19.4
      8:
      - 3
      - 5
      13: windows-amd64
