_target_:
    value: jax.random.PRNGKey
_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 12
                - 45
                - 50
                - 55
            "2":
                - 12
                - 45
                - 50
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
batchsize:
    value: 10000
depth:
    value: 2
epochs:
    value: 20000
in_size:
    value: 4
l0_threshold:
    value: 0.001
loss_type:
    value: mse
lr_start:
    value: 0.0001
out_size:
    value: 1
seed:
    value: 0
sweep:
    value:
        command:
            - C:/Users/Simon/.conda/envs/EQL/python.exe
            - main_normal.py
        method: grid
        metric:
            goal: minimize
            name: val_loss
        name: sweep_normal
        parameters:
            _target_:
                value: jax.random.PRNGKey
            batchsize:
                value: 10000
            depth:
                value: 2
            epochs:
                value: 20000
            in_size:
                values:
                    - 2
                    - 3
                    - 4
            l0_threshold:
                value: 0.001
            loss_type:
                value: mse
            lr_start:
                values:
                    - 0.001
                    - 0.0001
            out_size:
                value: 1
            seed:
                values:
                    - 0
                    - 1
            width_size:
                value:
                    - 15
                    - 18
                    - 21
        program: main_normal.py
wandb:
    value:
        setup:
            entity: simonb03-university-of-t-bingen
width_size:
    value: 21
