_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 2
                - 16
                - 23
                - 24
                - 55
            "4": 3.12.7
            "5": 0.19.4
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
Batchsize:
    value: 1000
Reg_Factor:
    value: 0.1
Threshold_div:
    value: 1/sqrt(t+1)
Threshold_mask:
    value: 0.001
architecture:
    value: EQLdiv_2_Layers
epochs:
    value: 20000
input_dim:
    value: 4
learning_rate:
    value: 0.0001
optimizer:
    value: Adam
output_dim:
    value: 1
regularization:
    value: No_reg(5000)+L1(14000)+Pruning(1000)
