wandb_version: 1

_target_:
  value: jax.random.PRNGKey
batchsize:
  value: 10000
depth:
  value: 2
epochs:
  value: 20000
in_size:
  value: 3
l0_threshold:
  value: 0.001
loss_type:
  value: mse
lr_start:
  value: 0.001
out_size:
  value: 1
seed:
  value: 12
width_size:
  value: 18
