_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 12
                - 45
                - 50
                - 55
            "2":
                - 12
                - 45
                - 50
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
depth:
    value: 2
in_size:
    value: 2
init_seed:
    value: 21
lr_start:
    value: 0.001
reg_factor:
    value: 0.1
seed:
    value: 10
sweep:
    value:
        command:
            - C:/Users/Simon/.conda/envs/EQL/python.exe
            - main_normal.py
        method: grid
        metric:
            goal: minimize
            name: val_loss
        name: L1_sweep_2
        parameters:
            depth:
                values:
                    - 1
                    - 2
                    - 3
            in_size:
                value: 2
            init_seed:
                values:
                    - 21
                    - 22
                    - 23
                    - 24
                    - 25
                    - 26
                    - 27
                    - 28
                    - 29
                    - 30
            lr_start:
                values:
                    - 0.005
                    - 0.001
                    - 0.0005
                    - 0.0001
            reg_factor:
                values:
                    - 0.1
                    - 0.05
                    - 0.01
                    - 0.005
                    - 0.001
                    - 0.0005
                    - 0.0001
                    - 5e-05
                    - 1e-05
            seed:
                value: 0
            width_size:
                values:
                    - 12
                    - 15
                    - 18
        program: main_normal.py
wandb:
    value:
        setup:
            entity: simonb03-university-of-t-bingen
width_size:
    value: 18
