wandb_version: 1

sweep:
  desc: null
  value:
    program: main_normal.py
    name: sweep
    metric:
      name: val_loss
      goal: minimize
    method: grid
    parameters:
      exp.model.in_size:
        values:
        - 1
        - 2
        - 4
      exp.model.out_size:
        value: 1
      exp.model.width_size:
        values:
        - 6
        - 15
        - 21
      exp.model.depth:
        values:
        - 1
        - 2
      exp.model.key._target_:
        value: jax.random.PRNGKey
      exp.model.key.seed:
        values:
        - 0
        - 1
      opt.epochs:
        value: 20000
      opt.batchsize:
        value: 10000
      opt.loss_type:
        value: mse
      opt.lr_start:
        values:
        - 0.01
        - 0.0001
      opt.l0_threshold:
        value: 0.001
    command:
    - C:/Users/Simon/.conda/envs/EQL/python.exe
    - main_normal.py
    - wandb.setup.entity=simonb03-university-of-t-bingen
exp:
  desc: null
  value:
    model:
      in_size: 4
      out_size: 1
      width_size: 21
      depth: 2
      key:
        _target_: jax.random.PRNGKey
        seed: 0
opt:
  desc: null
  value:
    epochs: 20000
    batchsize: 10000
    loss_type: mse
    lr_start: 0.0001
    l0_threshold: 0.001
wandb:
  desc: null
  value:
    setup:
      entity: simonb03-university-of-t-bingen
_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739279377
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      - 37
      4: 3.11.11
      5: 0.19.4
      8:
      - 3
      - 5
      13: windows-amd64
exp.model.depth:
  desc: null
  value: 1
exp.model.in_size:
  desc: null
  value: 1
exp.model.key._target_:
  desc: null
  value: jax.random.PRNGKey
exp.model.key.seed:
  desc: null
  value: 0
exp.model.out_size:
  desc: null
  value: 1
exp.model.width_size:
  desc: null
  value: 21
opt.batchsize:
  desc: null
  value: 10000
opt.epochs:
  desc: null
  value: 20000
opt.l0_threshold:
  desc: null
  value: 0.001
opt.loss_type:
  desc: null
  value: mse
opt.lr_start:
  desc: null
  value: 0.0001
