# Create sweep:
# wandb sweep conf\sweep\sweep.yaml -e simonb03-university-of-t-bingen -p OPR_sweep_4_seed


program: main_OPR.py
name: OPR_sweep_4_seed
metric:
  name: val_loss
  goal: minimize

method: grid

parameters:
  in_size: 
    value: 4
  out_size: 
    value: 1
  width_size: 
    value: 15
  depth: 
    value: 2
  _target_: 
    value: jax.random.PRNGKey
  seed:
    values: [0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

  epochs: 
    value: 20000
  batchsize: 
    value: 10000
  loss_type: 
    value: 'mse'
  lr_start:
    value: 1e-3
  l0_threshold:
    value: 1e-3

command:
  - C:/Users/Simon/.conda/envs/EQL/python.exe
  - main_OPR.py
# - wandb.setup.entity=simonb03-university-of-t-bingen
