# Create sweep:
# wandb sweep conf\sweep\sweep.yaml -e simonb03-university-of-t-bingen -p sweep_OPR_val


program: main_OPR.py
name: sweep_OPR_val
metric:
  name: val_loss
  goal: minimize

method: grid

parameters:
  in_size: 
    values: [2, 3, 4]
  out_size: 
    value: 1
  width_size: 
    values: [15, 18, 21]
  depth: 
    value: 2
  _target_: 
    value: jax.random.PRNGKey
  seed:
    values: [0, 1]

  epochs: 
    value: 20000
  batchsize: 
    value: 10000
  loss_type: 
    value: 'mse'
  lr_start:
    values: [1e-3, 1e-4]
  l0_threshold:
    value: 1e-3

command:
  - C:/Users/Simon/.conda/envs/EQL/python.exe
  - main_OPR.py
# - wandb.setup.entity=simonb03-university-of-t-bingen
