_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 12
                - 45
                - 50
                - 55
            "2":
                - 12
                - 45
                - 50
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
depth:
    value: 3
in_size:
    value: 4
init_seed:
    value: 29
lr_start:
    value: 0.001
reg_factor:
    value: 0.001
seed:
    value: 0
sweep:
    value:
        command:
            - python
            - main_OPR.py
        method: grid
        metric:
            goal: minimize
            name: val_loss
        name: OPR_sweep_4
        parameters:
            depth:
                values:
                    - 1
                    - 2
                    - 3
            in_size:
                value: 4
            init_seed:
                values:
                    - 21
                    - 22
                    - 23
                    - 24
                    - 25
                    - 26
                    - 27
                    - 28
                    - 29
                    - 30
            lr_start:
                value: 0.001
            reg_factor:
                values:
                    - 0.005
                    - 0.001
                    - 0.0005
                    - 0.0001
                    - 5e-05
            seed:
                value: 0
            width_size:
                values:
                    - 12
                    - 15
                    - 18
        program: main_OPR.py
wandb:
    value:
        setup:
            entity: simonb03-university-of-t-bingen
width_size:
    value: 15
